name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["lts/-1", "lts/*"]
    name: Test on node@${{ matrix.node }}
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      - name: Enable Corepack ğŸ”§
        run: npx corepack enable
      - name: Setup node ğŸ”§
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install ğŸª„
        run: yarn install --frozen-lockfile
      - name: Lint ğŸ”
        run: yarn run lint
      - name: Prettier ğŸ”
        run: yarn run prettycheck
      - name: TypeScript ğŸ”
        run: yarn run typecheck
      - name: Jest ğŸ”
        run: yarn run spec
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["lts/-1", "lts/*"]
    name: Build on node@${{ matrix.node }}
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
      - name: Enable Corepack ğŸ”§
        run: npx corepack enable
      - name: Setup node ğŸ”§
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - name: Install ğŸª„
        run: yarn install --frozen-lockfile
      - name: Build ğŸ’
        run: yarn run build
